### ISSUE TITLE
Domain cancelation status

### ISSUE THREAD

**Issue by RamonSmit** [hiddeco/transip#17]
Hi there, 

Thanks for this wonderful package! I really appreciate that you put in this much time and effort to create such a nice package.

I've got one question, is there a possible way to check if a owned domain name is canceled? 

Thanks in advance,
Ramon

**Comment by petericebear** [comment]
Hi Ramon,

When you get the domain details you would see a cancellationDate.

`{
  "domain": {
    "name": "example.com",
    "authCode": "kJqfuOXNOYQKqh/jO4bYSn54YDqgAt1ksCe+ZG4Ud4nfpzw8qBsfR2JqAj7Ce12SxKcGD09v+yXd6lrm",
    "isLocked": false,
    "registrationDate": "2016-01-01",
    "renewalDate": "2017-01-01",
    "isWhitelabel": false,
    "cancellationDate": "2017-01-01 12:00:00",
    "cancellationStatus": "signed",
    "isDnsOnly": false,
    "tags": [
      "customTag",
      "anotherTag"
    ]
  }
}`

**Comment by RamonSmit** [comment]
Hi Peter,

Thanks for your answer, What are you doing to get those results? 
I'm using: 
```
->domainService()->getInfo('example.com')
```
But I do not get those results like yours.

Thanks in advance,
Ramon

**Comment by petericebear** [comment]
I got those from the REST api, but that is not available for everyone, let me check what the response is. Maybe the model does not have that field, but maybe it can be added to it.

**Comment by petericebear** [comment]
You are right, that field is not present in the result. I will contact them about it.

**Comment by RamonSmit** [comment]
Thanks Peter!

**Comment by RamonSmit** [comment]
Hi @petericebear 

Did you hear anything in return from TransIP?

Thanks in advance!

**Comment by petericebear** [comment]
Hi Ramon,
Sorry for late reply. The soap api wont change at this time. You can send a support ticket and ask for the activation of the REST api. I use the SOAP and REST api for some functionalities..

More info about the docs can be found here in advance: https://api.transip.nl/rest/docs.html.
If you have any more questions about it let me know.

**Comment by RamonSmit** [comment]
Yes! Got in contact with them, they've enabled the REST Api for me! 

Thanks for the heads up! :-)

**Comment by baristacoder** [comment]
@RamonSmit let me know if you encounter some problems. I use it with the Laravel Framework, if you need some code or help contact me.

**Comment by petericebear** [comment]
@RamonSmit let me know if you encounter some problems. I use it with the Laravel Framework, if you need some code or help contact me.
