### ISSUE TITLE
VPS VNC throwing Deprecated

### ISSUE THREAD

**Issue by janyksteenbeek** [hiddeco/transip#6]
When using `getVps` to retrieve more information about a VPS, the values of the VNC properties are all `Deprecated`

```
+vncHostname: "Deprecated"
+vncPortNumber: "Deprecated"
+vncPassword: "Deprecated"
```

Is this because the package is still using an old version of the TransIP API?

---

**Update:** Looks like this is also happening with TransIP's official library. Submitted a ticket and now awaiting response from the TransIP team. Will keep you up2date

**Comment by hiddeco** [comment]
@janyksteenbeek the current package is one minor release further then the official TransIP API at the moment. So that shouldn't be the problem :-)

Can you keep us posted about your ticket so that we can resolve the issue asap?

**Comment by janyksteenbeek** [comment]
Just got a response from the TransIP team:

> Momenteel is het helaas niet mogelijk om gebruik te maken van VNC via de API. Aangezien dit voor de veiligheid van je VPS'en aanzienlijke consequenties kan hebben, hebben wij deze functionaliteit voor nu volledig uitgeschakeld. Wij zijn aan het onderzoeken of en op welke manier wij dit alsnog op een veilige manier kunnen implementeren. Momenteel kan ik hier alleen nog geen datum aan koppelen.

In short, TransIP disabled this for all account because of 'security reasons'.. Thanks though!
