### ISSUE TITLE
companyType seems to have become a required field

### ISSUE THREAD

**Issue by websmurf** [hiddeco/transip#8]
Hi Hidde

Thanks for your library, makes handling the Transip API a bit easier. 

The companyType property seems to have become a required field for a WhoisContact. I'm getting the following error if I don't add it to a contact:

> SOAP-ERROR: Encoding: object has no 'companyType' property

If I add it to the contact object manually, it works:
```
        $contact              = new WhoisContact();
        $contact->type        = WhoisContact::TYPE_TECHNICAL;
        $contact->companyName = 'Bandhosting.nl';
        $contact->companyType = ''; # this is new
        $contact->firstName   = 'Adam';
        $contact->lastName    = 'van Dongen';
        $contact->street      = 'Slijpsteen';
        $contact->number      = 8;
        $contact->postalCode  = '4906 LP';
        $contact->city        = 'Oosterhout';
        $contact->country     = 'NL';
        $contact->phoneNumber = '+31652411220';
        $contact->email       = 'adam@bandhosting.nl';
        $contacts[]           = $contact;
```

It seem to be missing from the Model definition as well although there is a variable `$possibleCompanyTypes` in there.

**Comment by websmurf** [comment]
Running into another thing after adding the companyType attribute. 
Now I'm getting this error: 

> Invalid API signature, signature does not match the request.

Which seems a bit odd since the getInfo request seems to work fine with the same key.
Any idea what that could be?

**Comment by hiddeco** [comment]
Yelp, that's not what it's supposed to do. I'll push a fix later today. 

Can you please provide me the whole structure you're trying to pass to the API for the second issue?

**Comment by petericebear** [comment]
What I suggest is setting the companyType to 'ANDERS' when company name is set. Then there should be no problems setting the Whois data.

**Comment by hiddeco** [comment]
@petericebear shouldn't it officially be `EENMANSZAAK` as Bandhosting.nl is a sole trader?

**Comment by websmurf** [comment]
Will try that once im back behind my pc. I wonder where the business type is needed anyway, since you cant enter it through the CP of TransIp anyway

**Comment by hiddeco** [comment]
I just released version `5.3.2` which adds the missing `companyType` property.

**Comment by petericebear** [comment]
TransIP does not use it anymore on the customers.

**Comment by websmurf** [comment]
Thanks! Will try it out somewhere in the weekend 😄

**Comment by websmurf** [comment]
Sorry, took me a bit longer to update. Could you also update the laravel-transip package to reflect the new version? It's requiring 5.3 of the transip package, not 5.3.*

**Comment by websmurf** [comment]
Have manually tried your fix, and that resolves the initial error I had. 
In regards to the API signature error, this is my call to the transip function:

`TransIP::domain()->setContacts('bandhosting.nl', $contacts);`

Where contacts is: 
```
Array
(
    [0] => TransIP\Model\WhoisContact Object
        (
            [type] => registrant
            [firstName] => AAL
            [middleName] => 
            [lastName] => van Dongen
            [companyName] => Bandhosting.nl
            [companyType] => 
            [companyKvk] => 
            [street] => Zeggeweg
            [number] => 6
            [postalCode] => 4924 EC
            [city] => Drimmelen
            [phoneNumber] => +31 652411220
            [faxNumber] => 
            [email] => adam@bandhosting.nl
            [country] => nl
        )

    [1] => TransIP\Model\WhoisContact Object
        (
            [type] => administrative
            [firstName] => AAL
            [middleName] => 
            [lastName] => van Dongen
            [companyName] => Bandhosting.nl
            [companyType] => 
            [companyKvk] => 
            [street] => Zeggeweg
            [number] => 6
            [postalCode] => 4924 EC
            [city] => Drimmelen
            [phoneNumber] => +31 652411220
            [faxNumber] => 
            [email] => adam@bandhosting.nl
            [country] => nl
        )

    [2] => TransIP\Model\WhoisContact Object
        (
            [type] => technical
            [firstName] => Adam
            [middleName] => 
            [lastName] => van Dongen
            [companyName] => Bandhosting.nl
            [companyType] => 
            [companyKvk] => 
            [street] => Slijpsteen
            [number] => 8
            [postalCode] => 4906 LP
            [city] => Oosterhout
            [phoneNumber] => +31652411220
            [faxNumber] => 
            [email] => adam@bandhosting.nl
            [country] => NL
        )

)
```

I have double checked that in my config/transip.php file, the main connection mode has been set to `readwrite`

**Comment by websmurf** [comment]
For your informatie, the setDnsEntries does work, also i've tried splitting up the contact and owner and update the registrant through the setOwner method, that resulted in the same error

**Comment by hiddeco** [comment]
@websmurf in your example, is `companyType` an empty string or a `null` value?

**Comment by websmurf** [comment]
It's an empty string

**Comment by hiddeco** [comment]
@websmurf and if you try passing one of the `WhoisContact::$possibleCompanyTypes` values?

**Comment by websmurf** [comment]
Same error I'm afraid. Btw, empty string is one of the allowed $possibleCompanyTypes values
I must say that I'm using the 5.3. package since laravel-transip requires that version and a composer update isn't possible due to resolution errors

I've applied the change in the model for companyType manually, but I don't know if there are changes in 5.3.1 that might resolve this issue?

**Comment by hiddeco** [comment]
@websmurf please check if the issue is resolved with the property ordering change in 3a71d2828b1055db3e0c0128a2a511022a5a2017. 

Instead of throwing an `Uncaught SoapFault exception: [204] Invalid API signature, signature does not match the request.` it gives me 

```
Uncaught SoapFault exception: [302] There seems to be a problem with your administrative contact:
 - Je hebt een ongeldig telefoonnummer ingevuld.
```

which should be a good sign.

**Comment by websmurf** [comment]
Yep, with that change applied, it works as expected. 
Thanks! 

Have created a pull request for laravel-transip to bump for the correct version number in the composer.json file. See here: https://github.com/hiddeco/laravel-transip/pull/6

**Comment by hiddeco** [comment]
@websmurf thanks for your contribution, [version 5.3.3](https://github.com/hiddeco/transip/tree/v5.3.3) has been tagged and released and your PR has been merged and is available under `hiddeco/laravel-transip` [version 5.3.2](https://github.com/hiddeco/laravel-transip/tree/v5.3.2)

**Comment by websmurf** [comment]
Thanks!
